import { NextRequest, NextResponse } from "next/server";
import puppeteer from "puppeteer";
import fs from "fs";

function getChromeExecutablePath(): string | undefined {
  const possiblePaths = [
    "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
    process.env.CHROME_PATH || "",
  ];
  for (const p of possiblePaths) {
    if (p && fs.existsSync(p)) {
      return p;
    }
  }
  return undefined;
}

export async function POST(req: NextRequest) {
  try {
    const analysisData = await req.json();

    if (!analysisData) {
      return NextResponse.json({ error: "Missing analysis data payload" }, { status: 400 });
    }

    const {
      sentimentScore = {},
      summary = {},
      complaintCategories = [],
      trendChart = [],
      recurringIssues = [],
      executiveSummary = "",
      recommendations = [],
    } = analysisData;

    const healthScore = Math.round(sentimentScore.score ?? 75);
    const healthLabel = sentimentScore.healthLabel || sentimentScore.label || "Good";
    const statusMessage = sentimentScore.statusMessage || "Business Operating Normally";

    // Build standalone HTML template matching Analytics page dark design
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AI Business Analytics Report</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Inter', sans-serif;
      background-color: #09090b;
      color: #f4f4f5;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    .report-card {
      background-color: #121216;
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: 1rem;
    }
  </style>
</head>
<body class="p-6 space-y-6">

  <!-- Header Banner -->
  <div class="report-card p-6 flex items-center justify-between border-blue-500/20">
    <div class="space-y-1">
      <div class="flex items-center gap-2">
        <span class="text-xs px-2.5 py-0.5 rounded-full bg-blue-500/20 text-blue-400 font-mono font-bold">
          AI INTELLIGENCE REPORT
        </span>
        <span class="text-xs text-zinc-400 font-mono">
          ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
        </span>
      </div>
      <h1 class="text-2xl font-extrabold text-white tracking-tight">
        Executive Business Analytics & Health Assessment
      </h1>
      <p class="text-xs text-zinc-400">
        Generated by Gemini 3 Flash • Multi-Dimensional Customer Feedback Pipeline
      </p>
    </div>
    <div class="text-right font-mono text-xs text-zinc-400">
      <div>Total Reviews Analyzed</div>
      <div class="text-xl font-bold text-white">${summary.totalReviews || 0}</div>
    </div>
  </div>

  <!-- Business Health Score Banner -->
  <div class="report-card p-6 space-y-4">
    <h2 class="text-sm font-bold text-zinc-400 uppercase font-mono tracking-wider">
      1. Business Health Score Assessment
    </h2>
    <div class="grid grid-cols-3 gap-6 items-center">
      <!-- Score Circle Gauge -->
      <div class="flex flex-col items-center justify-center p-4 rounded-2xl bg-white/[0.02] border border-white/10 text-center">
        <div class="text-5xl font-extrabold text-blue-400 font-mono">${healthScore}</div>
        <div class="text-xs text-zinc-400 mt-1 font-medium">Out of 100 Points</div>
      </div>

      <!-- Health Label & Status -->
      <div class="col-span-2 space-y-2">
        <div class="flex items-center gap-3">
          <span class="text-lg font-bold text-white">${healthLabel}</span>
          <span class="text-xs px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 font-semibold">
            ${statusMessage}
          </span>
        </div>
        <p class="text-xs text-zinc-300 leading-relaxed">
          Computed using 4-Factor Weighted Algorithm: 40% Sentiment Ratio, 30% Star Rating, 20% Complaint Rate, 10% Recurring Issue Severity.
        </p>
      </div>
    </div>
  </div>

  <!-- Key Metrics & Sentiment Breakdown Grid -->
  <div class="grid grid-cols-4 gap-4">
    <div class="report-card p-4 space-y-1">
      <div class="text-xs text-zinc-400 font-mono">Average Star Rating</div>
      <div class="text-2xl font-extrabold text-amber-400">${summary.averageRating || 0} ⭐</div>
    </div>
    <div class="report-card p-4 space-y-1">
      <div class="text-xs text-emerald-400 font-mono">Positive Feedback</div>
      <div class="text-2xl font-extrabold text-emerald-400">${sentimentScore.positivePercentage || 0}%</div>
      <div class="text-[10px] text-zinc-400">${summary.positiveCount || 0} reviews</div>
    </div>
    <div class="report-card p-4 space-y-1">
      <div class="text-xs text-zinc-400 font-mono">Neutral Feedback</div>
      <div class="text-2xl font-extrabold text-zinc-300">${sentimentScore.neutralPercentage || 0}%</div>
      <div class="text-[10px] text-zinc-400">${summary.neutralCount || 0} reviews</div>
    </div>
    <div class="report-card p-4 space-y-1">
      <div class="text-xs text-red-400 font-mono">Negative Feedback</div>
      <div class="text-2xl font-extrabold text-red-400">${sentimentScore.negativePercentage || 0}%</div>
      <div class="text-[10px] text-zinc-400">${summary.negativeCount || 0} reviews</div>
    </div>
  </div>

  <!-- Top Complaint Categories Table -->
  ${
    complaintCategories.length > 0
      ? `
  <div class="report-card p-6 space-y-3">
    <h2 class="text-sm font-bold text-zinc-400 uppercase font-mono tracking-wider">
      2. Top Complaint Categories
    </h2>
    <table class="w-full text-left text-xs">
      <thead>
        <tr class="text-zinc-500 font-mono text-[10px] uppercase border-b border-white/10">
          <th class="pb-2">Category</th>
          <th class="pb-2">Count</th>
          <th class="pb-2">Percentage</th>
          <th class="pb-2">Severity</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-white/5 text-zinc-300">
        ${complaintCategories
          .map(
            (c: any) => `
          <tr>
            <td class="py-2.5 font-semibold text-white">${c.category}</td>
            <td class="py-2.5 font-mono">${c.count}</td>
            <td class="py-2.5 font-mono text-blue-400 font-bold">${c.percentage}%</td>
            <td class="py-2.5">
              <span class="px-2 py-0.5 rounded text-[10px] font-mono font-bold ${
                c.severity?.toLowerCase() === "high" || c.severity?.toLowerCase() === "critical"
                  ? "bg-red-500/20 text-red-400 border border-red-500/30"
                  : "bg-amber-500/20 text-amber-400 border border-amber-500/30"
              }">
                ${c.severity || "Medium"}
              </span>
            </td>
          </tr>
        `
          )
          .join("")}
      </tbody>
    </table>
  </div>
  `
      : ""
  }

  <!-- Recurring Operational Issues -->
  ${
    recurringIssues.length > 0
      ? `
  <div class="report-card p-6 space-y-3">
    <h2 class="text-sm font-bold text-zinc-400 uppercase font-mono tracking-wider">
      3. Recurring Issues & Operational Friction
    </h2>
    <div class="space-y-3">
      ${recurringIssues
        .map(
          (issue: any) => `
        <div class="p-3.5 rounded-xl bg-white/[0.02] border border-white/10 space-y-1.5">
          <div class="flex items-center justify-between">
            <span class="text-xs font-bold text-white">${issue.title}</span>
            <span class="text-[10px] font-mono px-2 py-0.5 rounded bg-red-500/10 text-red-400 border border-red-500/20">
              ${issue.severity || "High"}
            </span>
          </div>
          ${
            issue.sampleQuote
              ? `<p class="text-xs text-zinc-300 italic">"${issue.sampleQuote}"</p>`
              : ""
          }
          ${
            issue.impact
              ? `<p class="text-[11px] text-zinc-400 font-mono">Impact: ${issue.impact}</p>`
              : ""
          }
        </div>
      `
        )
        .join("")}
    </div>
  </div>
  `
      : ""
  }

  <!-- Executive Summary & McKinsey Action Plan -->
  <div class="report-card p-6 space-y-4">
    <h2 class="text-sm font-bold text-zinc-400 uppercase font-mono tracking-wider">
      4. Executive Summary & Recommended Actions
    </h2>
    ${
      executiveSummary
        ? `
      <div class="p-4 rounded-xl bg-blue-500/10 border border-blue-500/20 text-xs text-zinc-200 leading-relaxed font-sans">
        ${executiveSummary}
      </div>
    `
        : ""
    }

    ${
      recommendations.length > 0
        ? `
      <div class="space-y-2 pt-2">
        <div class="text-xs font-bold text-white uppercase font-mono">Strategic Action Items</div>
        <ul class="space-y-2 text-xs text-zinc-300">
          ${recommendations
            .map(
              (rec: string, i: number) => `
            <li class="flex items-start gap-2.5 p-2.5 rounded-lg bg-white/[0.02] border border-white/5">
              <span class="font-mono font-bold text-blue-400">${i + 1}.</span>
              <span>${rec}</span>
            </li>
          `
            )
            .join("")}
        </ul>
      </div>
    `
        : ""
    }
  </div>

</body>
</html>
    `;

    // Detect installed Chrome executable path on Windows OS
    const chromePath = getChromeExecutablePath();

    // Launch Puppeteer headless browser instance
    const browser = await puppeteer.launch({
      headless: true,
      executablePath: chromePath,
      args: ["--no-sandbox", "--disable-setuid-sandbox", "--font-render-hinting=none"],
    });

    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "domcontentloaded" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "10mm",
        bottom: "10mm",
        left: "10mm",
        right: "10mm",
      },
    });

    await browser.close();

    // Convert Uint8Array to Buffer to satisfy Next.js BodyInit type
    const responseBuffer = Buffer.from(pdfBuffer);

    return new NextResponse(responseBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": 'attachment; filename="AI_Business_Analytics_Report.pdf"',
      },
    });
  } catch (error: any) {
    console.error("Puppeteer PDF Generation Error:", error);
    return NextResponse.json({ error: error?.message || "Failed to generate PDF report" }, { status: 500 });
  }
}
